parameters:
    admin_zero:
        developer: Developer
        sidebar:
            
            - 
                model: Redirecciones
                label: Redirecciones
                ico: home